### ISSUE TITLE
Allow link directive to link to another SPA without knowing the full URL

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux-router#5]
This feature will also check security/permissions for a given SPA link.

**This is not the final solution, but more of an idea:**

Update skyAppLink to support "SPA" property.  Deprecate skyAppLinkExternal.  Add new "App" property to skyAppLink and branch on whether link is in same SPA or whether link talks to nav service.  In SPAs bootstrap, reach out to nav service to get "ReferencedRoutes" resolved and saved in config.

This should also include an update similar to how https://github.com/blackbaud/skyux-i18n/blob/master/src/app/public/modules/i18n/resources.service.ts works, where the first time a URL is requested talk to the Nav Service to get the resolved fully qualified URLs.

**Comment by Blackbaud-SteveBrush** [comment]
Related: https://github.com/blackbaud/skyux-router/issues/7

**Comment by Blackbaud-AlexKingman** [comment]
Closing. Duplicate of https://github.com/blackbaud/skyux-router/issues/7.
